### ISSUE TITLE
Builder pattern

### ISSUE THREAD

**Issue by paulofaria** [formbound/Paramount#1]
This looks very good. How about using the builder pattern to create the validation rules and them just apply the value to the validator once?

I used this pattern with [Spell](https://github.com/Zewo/Spell) to create the routes.
The idea is something like this:

```swift
protocol ValidationRule {
}

struct IntegerValidationRule: ValidationRule {
}

struct StringValidationRule: ValidationRule {
}

struct ValidType {
    // Maybe this struct can wrap the original type
    // and based on the validation rules
    // and that the value is valid
    // it can provide type-safe accessors to the underlying value
}

struct Validator {
    public final class ValidatorBuilder {
        var rules: [ValidationRule] = []
        public func integer(key: String, minValue: Int = Int.min, maxValue: Int = Int.max) {
            // create a rule based on the arguments
            rules.append(IntegerValidationRule())
        }

        public func string(key: String, minLength: Int = 0, maxLength: Int = Int.max) {
            // create a rule based on the arguments
            rules.append(StringValidationRule())
        }

        public func type<T>(key: String, type: T.Type) {
            // maybe support validation that a value must be of type T?
            // maybe create a protocol that lets people create custom validation rules
            // for custom types?
            rules.append(CustomTypeValidationRule())
        }

        // you can even nest rules inside rules
        // check the Spell method called groups which lets you create routes within routes
        // you can do this to validate dictionaries inside of dictionaries
    }

    let rules: [ValidationRule] = []

    public init(build: (validator: ValidatiorBuilder) -> Void) {
        let builder = ValidatorBuilder()
        build(validator: builder)
        self.rules = builder.rules
    }

    public func validate(value: Any) throws -> ValidType {
        // use the rules to validate the value
        // if the value is valid you can return a wrapper
        // that could implement subscripts for dictionaries
        // for example, to make it easier to extract the values
        // this part I'm not sure if would work
    }
}



// Usage


let validator = Validator { v in
    v.integer("key for int", maxValue: 10)
    v.string("key for string")
}

let value = [
    "something": "something"
]

do {
    let validValue = validator.validate(value)
    let something = validValue["something"] // returns a String, not a String? as usual
} catch {
    // some validation error
}
```

Notice I never used the word *object*, because in Swift an object implies that it is an instance of a class, and we can have structs which are much more appropriate for plain data. The term used throughout is **type**, which could be a class, a struct, an enum, etc. What is usually called *object* is called value. I know this can be a bit confusing at first, but when you get used to it makes much more sense.

Maybe this ideas make sense. I don't know, haha. But I guess that's how I would try to design it.

**Comment by formbound** [comment]
I like this! I think a builder pattern is good, to make the code easier to write. My take is pretty verbose, and i think a more modular approach where multiple validators can be added to a key would be better. Type terminology also makes sense. I'm going to keep exploring this, and hopefully end up with something that will work well with your code base!

**Comment by paulofaria** [comment]
Notice also that the validate function could receive just `Any`. This means you could validate types outside of a dictionary. If I wanted to simply validate that an Int is inside a range, I should be able to do it without having to put it in a dictionary. To make this change, the functions in the builder would have to drop the `key` argument and a new function should be created. This function would get a key in its argument and a them inside it I could apply more rules. The usage would be something like this;

For a single Int:

```swift
let validator = Validator { rule in
    rule.integer(minValue: 0, maxValue: 100)
}

do {
    try validator.validate(50)
    try validator.validate(200)
} catch {
    // 200 out of range
}
```

For a dictionary:

```swift
let validator = Validator { rule in
    rule.key("language") { rule in
        rule.string(acceptedValues: "swift", "ruby", "haskell") // Variadic parameters
    }
}

do {
    try validator.validate(["language": "swift"])
    try validator.validate(["language": "java"])
} catch {
    // "java" not accepted
}
```

**Comment by formbound** [comment]
A nice feature would be to have the type inferred from the property being assigned the validated value, much like i've tried to do. I guess my take was to use an unwrapped optional, as being optional is something being declared in the validator. That might not make sense if one should be able to validate non-dictionary contained data though. One take would be to split methods into one called `require` and one called `optional` instead of just `validate`. I'll explore the different possibilities.
